<a href="https://colab.research.google.com/github/Satyakadumula009/IMDB-SQL-Project/blob/main/Project_SQL_Query_IMDB_Dataset_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3 as sql

In [ ]:
# from operator import methodcaller
# 1.connect to database or create a connection --> sql.connect(database_name)
# 2.using the cursor function --> database_variable.cursor()

# workflow:
# 1. establish a connection to sqlite database by creating a connection_object
# 2. create a cursor_object using cursor() method
# 3. execute the query --> cursor_object.execute('query')
# 4. To fetch the data, use fetchall() method of the cursor_object.

In [ ]:
db = '/content/drive/MyDrive/Python/movie.sqlite'
con = sql.connect(db)
cur = con.cursor()

In [ ]:
cur.execute('Select * from movies')
movies = cur.fetchall()

In [ ]:
# To open the 'movies' table
df = pd.DataFrame(movies, columns = ['id', 'original_title', 'budget', 'popularity', 'release_date', 'revenue', 'title', 'vote_average', 'vote_count', 'overview', 'tagline', 'uid', 'director_id'])
df.head(3)

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
0,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762
1,43598,Pirates of the Caribbean: At World's End,300000000,139,2007-05-19,961000000,Pirates of the Caribbean: At World's End,6.9,4500,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",285,4763
2,43599,Spectre,245000000,107,2015-10-26,880674609,Spectre,6.3,4466,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,206647,4764

In [ ]:
df.shape

(0, 13)

In [ ]:
df.head(3)

,id,original_title,budget,popularity,release_date,revenue,title,vote_average,vote_count,overview,tagline,uid,director_id
0,43597,Avatar,237000000,150,2009-12-10,2787965087,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di...",Enter the World of Pandora.,19995,4762
1,43598,Pirates of the Caribbean: At World's End,300000000,139,2007-05-19,961000000,Pirates of the Caribbean: At World's End,6.9,4500,"Captain Barbossa, long believed to be dead, ha...","At the end of the world, the adventure begins.",285,4763
2,43599,Spectre,245000000,107,2015-10-26,880674609,Spectre,6.3,4466,A cryptic message from Bond’s past sends him o...,A Plan No One Escapes,206647,4764

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4773 entries, 0 to 4772
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              4773 non-null   int64
 1   original_title  4773 non-null   object
 2   budget          4773 non-null   int64
 3   popularity      4773 non-null   int64
 4   release_date    4773 non-null   object
 5   revenue         4773 non-null   int64
 6   title           4773 non-null   object
 7   vote_average    4773 non-null   float64
 8   vote_count      4773 non-null   int64
 9   overview        4770 non-null   object
 10  tagline         3951 non-null   object
 11  uid             4773 non-null   int64
 12  director_id     4773 non-null   int64
dtypes: float64(1), int64(7), object(5)
memory usage: 484.9+ KB

In [ ]:
# To open the 'directors' table

cur.execute('select * from directors')
director = cur.fetchall()

In [ ]:
df = pd.DataFrame(director,columns = ['name','id','gender','uid','department'])
df

                   name    id  gender      uid department
0         James Cameron  4762       2     2710  Directing
1        Gore Verbinski  4763       2     1704  Directing
2            Sam Mendes  4764       2       39  Directing
3     Christopher Nolan  4765       2      525  Directing
4        Andrew Stanton  4766       2        7  Directing
...                 ...   ...     ...      ...        ...
2344      Shane Carruth  7106       2    76624  Directing
2345   Neill Dela Llana  7107       0  1174437  Directing
2346        Scott Smith  7108       0  1219158  Directing
2347        Daniel Hsia  7109       2   208138  Directing
2348   Brian Herzlinger  7110       2    85563  Directing

[2349 rows x 5 columns]

In [ ]:
df.shape

(4773, 13)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2349 entries, 0 to 2348
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        2349 non-null   object
 1   id          2349 non-null   int64
 2   gender      2349 non-null   int64
 3   uid         2349 non-null   int64
 4   department  2349 non-null   object
dtypes: int64(3), object(2)
memory usage: 91.9+ KB

In [ ]:
# To find the no of movies present in iMDB

cur.execute('select count(*) from movies;')
count = cur.fetchall()
count

[(4773,)]

In [ ]:
# To find directors: James Cameron; Luc Besson; John Woo

cur.execute("select * from directors where name == 'James Cameron' or name == 'Luc Besson' or name == 'John Woo';")
dir3 = cur.fetchall()
dir3 = pd.DataFrame(dir3,columns = ['name','id','gender','uid','profession role'])
dir3

            name    id  gender    uid profession role
0  James Cameron  4762       2   2710       Directing
1       John Woo  4893       2  11401       Directing
2     Luc Besson  4949       2     59       Directing

In [ ]:
# To find all the directors whose names start with Steven

cur.execute('select * from directors where name like "Steven%";')
steven = cur.fetchall()
steven

[('Steven Spielberg', 4799, 2, 488, 'Directing'),
 ('Steven Soderbergh', 4909, 2, 1884, 'Directing'),
 ('Steven Brill', 5013, 2, 32593, 'Directing'),
 ('Steven Zaillian', 5117, 2, 2260, 'Directing'),
 ('Steven Quale', 5216, 2, 93214, 'Directing'),
 ('Steven Seagal', 5221, 2, 23880, 'Directing'),
 ('Steven E. de Souza', 5390, 2, 1726, 'Directing'),
 ('Steven Shainberg', 5803, 2, 67795, 'Directing'),
 ('Steven R. Monroe', 6713, 2, 88039, 'Directing')]

In [ ]:
cur.execute('select count(*) from directors where gender==1')
gend = cur.fetchall()
gend

[(150,)]

In [ ]:
cur.execute("SELECT name FROM directors WHERE gender == 1 ORDER by id asc limit 1 OFFSET 9")
name10th = cur.fetchall()
name10th

[('Angelina Jolie',)]

In [ ]:
# To get the most popular movies

cur.execute('SELECT original_title FROM movies ORDER by popularity desc LIMIT 3;')
name = cur.fetchall()
name

[('Minions',), ('Interstellar',), ('Deadpool',)]

In [ ]:
# To find the huge budget made films
cur.execute('SELECT original_title FROM movies ORDER by budget desc LIMIT 3')
bankable = cur.fetchall()
bankable

[('Pirates of the Caribbean: On Stranger Tides',),
 ("Pirates of the Caribbean: At World's End",),
 ('Avengers: Age of Ultron',)]

In [ ]:
cur.execute('SELECT original_title FROM movies WHERE release_date >="2000-01-01" ORDER by vote_average desc LIMIT 1')
avg_vote = cur.fetchall()
avg_vote

[('Sardaarji',)]

In [ ]:
# To find the movies directed by Brenda Chapman

cur.execute('SELECT original_title FROM movies JOIN directors WHERE movies.director_id = directors.id AND directors.name = "Brenda Chapman"')
brenda = cur.fetchall()
brenda

[('Brave',)]

In [ ]:
# the director who is most bankable

cur.execute('select name from directors join movies where movies.director_id==directors.id group by directors.id order by sum(budget) desc limit 1')
name = cur.fetchall()
name

[('Steven Spielberg',)]

In [ ]:
# top 10 highest budget movies

cur.execute('select original_title,name,release_date,budget,revenue from movies as mo join directors as dr where mo.director_id==dr.id order by budget desc limit 10')
t10 = cur.fetchall()
t10=pd.DataFrame(t10,columns = ['Movie','Director','Released On','Budget','Revenue'])
t10

,Movie,Director,Released On,Budget,Revenue
0,Pirates of the Caribbean: On Stranger Tides,Rob Marshall,2011-05-14,380000000,1045713802
1,Pirates of the Caribbean: At World's End,Gore Verbinski,2007-05-19,300000000,961000000
2,Avengers: Age of Ultron,Joss Whedon,2015-04-22,280000000,1405403694
3,Superman Returns,Bryan Singer,2006-06-28,270000000,391081192
4,John Carter,Andrew Stanton,2012-03-07,260000000,284139100
5,Tangled,Byron Howard,2010-11-24,260000000,591794936
6,Spider-Man 3,Sam Raimi,2007-05-01,258000000,890871626
7,The Lone Ranger,Gore Verbinski,2013-07-03,255000000,89289910
8,The Dark Knight Rises,Christopher Nolan,2012-07-16,250000000,1084939099
9,Harry Potter and the Half-Blood Prince,David Yates,2009-07-07,250000000,933959197

In [ ]:
# the top 10 films

cur.execute('select original_title,name,release_date,budget,popularity,revenue from movies join directors where movies.director_id == directors.id order by popularity desc limit 10')
pop = cur.fetchall()
pop=pd.DataFrame(pop,columns = ['original_title','name','release_date','budget','popularity','revenue'])
pop

,original_title,name,release_date,budget,popularity,revenue
0,Minions,Kyle Balda,2015-06-17,74000000,875,1156730962
1,Interstellar,Christopher Nolan,2014-11-05,165000000,724,675120017
2,Deadpool,Tim Miller,2016-02-09,58000000,514,783112979
3,Guardians of the Galaxy,James Gunn,2014-07-30,170000000,481,773328629
4,Mad Max: Fury Road,George Miller,2015-05-13,150000000,434,378858340
5,Jurassic World,Colin Trevorrow,2015-06-09,150000000,418,1513528810
6,Pirates of the Caribbean: The Curse of the Bla...,Gore Verbinski,2003-07-09,140000000,271,655011224
7,Dawn of the Planet of the Apes,Matt Reeves,2014-06-26,170000000,243,710644566
8,The Hunger Games: Mockingjay - Part 1,Francis Lawrence,2014-11-18,125000000,206,752100229
9,Big Hero 6,Chris Williams,2014-10-24,165000000,203,652105443

In [ ]:
# most popular movies with vote average

cur.execute('select original_title,name,release_date,budget,popularity,vote_average from movies join directors where movies.director_id = directors.id order by popularity desc')
va = cur.fetchall()
va = pd.DataFrame(va,columns = ['original_title','name','release_date','budget','popularity','vote_average'])
va.head(10)

,original_title,name,release_date,budget,popularity,vote_average
0,Minions,Kyle Balda,2015-06-17,74000000,875,6.4
1,Interstellar,Christopher Nolan,2014-11-05,165000000,724,8.1
2,Deadpool,Tim Miller,2016-02-09,58000000,514,7.4
3,Guardians of the Galaxy,James Gunn,2014-07-30,170000000,481,7.9
4,Mad Max: Fury Road,George Miller,2015-05-13,150000000,434,7.2
5,Jurassic World,Colin Trevorrow,2015-06-09,150000000,418,6.5
6,Pirates of the Caribbean: The Curse of the Bla...,Gore Verbinski,2003-07-09,140000000,271,7.5
7,Dawn of the Planet of the Apes,Matt Reeves,2014-06-26,170000000,243,7.3
8,The Hunger Games: Mockingjay - Part 1,Francis Lawrence,2014-11-18,125000000,206,6.6
9,Big Hero 6,Chris Williams,2014-10-24,165000000,203,7.8

In [ ]:
cur.execute('select name,count(name),popularity,revenue from movies join directors where movies.director_id=directors.id group by directors.id order by count(name) desc')
count = cur.fetchall()
count = pd.DataFrame(count,columns = ['name','no.of.movies','popularity','revenue'])
count.head(10)

                name  no.of.movies  popularity    revenue
0   Steven Spielberg            27          75  786636033
1        Woody Allen            21          43  151119219
2     Clint Eastwood            20          15  128884132
3    Martin Scorsese            20          32  185770160
4          Spike Lee            16          45  184376254
5   Robert Rodriguez            16          85   39407616
6       Ridley Scott            16          37  310669540
7       Renny Harlin            15           7   10017322
8  Steven Soderbergh            15          76  362744280
9       Oliver Stone            14          39  167298192

In [ ]:
cur.execute('select original_title,release_date,budget,revenue,popularity,vote_average from movies join directors on movies.director_id=directors.id where name="Steven Spielberg"')
steven = cur.fetchall()
steven = pd.DataFrame(steven,columns = ['Movie','release date','budget','revenue','popularity','vote_avg'])
steven

,Movie,release date,budget,revenue,popularity,vote_avg
0,Indiana Jones and the Kingdom of the Crystal S...,2008-05-21,185000000,786636033,75,5.7
1,The BFG,2016-06-01,140000000,183345589,44,6.0
2,War of the Worlds,2005-06-28,132000000,591739379,48,6.2
3,The Adventures of Tintin,2011-10-25,130000000,371940071,89,6.7
4,Minority Report,2002-06-20,102000000,358372926,65,7.1
5,A.I. Artificial Intelligence,2001-06-29,100000000,235926552,34,6.8
6,The Lost World: Jurassic Park,1997-05-23,73000000,229074524,2,6.2
7,The Terminal,2004-06-17,60000000,219417255,57,7.0
8,Munich,2005-12-22,70000000,130358911,29,6.9
9,Hook,1991-12-11,70000000,300854823,33,6.6
10,War Horse,2011-12-25,66000000,177584879,29,7.0
11,Saving Private Ryan,1998-07-24,70000000,481840909,76,7.9
12,Lincoln,2012-11-09,65000000,275293450,36,6.7
13,Jurassic Park,1993-06-11,63000000,920100000,40,7.6
14,Catch Me If You Can,2002-12-25,52000000,352114312,73,7.7
15,Indiana Jones and the Last Crusade,1989-05-24,48000000,474171806,80,7.6
16,Bridge of Spies,2015-10-15,40000000,165478348,48,7.2
17,Amistad,1997-12-03,36000000,74000000,3,6.8
18,1941,1979-12-13,35000000,31755742,10,5.6
19,Indiana Jones and the Temple of Doom,1984-05-23,28000000,333000000,66,7.1
20,Schindler's List,1993-11-29,22000000,321365567,104,8.3
21,Raiders of the Lost Ark,1981-06-12,18000000,389925971,68,7.7
22,Close Encounters of the Third Kind,1977-11-16,20000000,303788635,52,7.2
23,The Color Purple,1985-12-18,15000000,146292009,17,7.7
24,Jaws,1975-06-18,7000000,470654000,50,7.5
25,E.T. the Extra-Terrestrial,1982-04-03,10500000,792910554,56,7.3
26,Twilight Zone: The Movie,1983-06-24,10000000,29450919,12,6.2